[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
meme_one = "6pd1a8TTiKytoML9juVyMYcXrborBndhSGZLsxAhmH96"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/stillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
